<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/seguimiento.php';
require_once __DIR__ . '/includes/company.php';
require_once __DIR__ . '/includes/cotizacion_pdf_renderer.php';
$token=trim((string)($_GET['t']??''));if(!preg_match('/^[a-f0-9]{64}$/i',$token)){http_response_code(404);exit('Enlace no válido.');}
$order=tracking_order_by_token($token);if(!$order){http_response_code(404);exit('El seguimiento ya no está disponible.');}
$orderId=(int)$order['id'];$items=tracking_order_items($orderId);$finance=tracking_payment_summary($orderId);$company=company_profile();
$pdf=new SimplePdf();$navy=[0.03,0.08,0.13];$red=[1.0,0.09,0.32];$yellow=[1.0,0.75,0.10];$green=[0.12,0.83,0.45];$slate=[0.32,0.38,0.44];$light=[0.95,0.97,0.98];$border=[0.78,0.82,0.86];
$brand=trim((string)($company['trade_name']?:$company['legal_name']?:'Colibrí Print'));$legal=trim((string)($company['legal_name']??''));$contact=trim(implode(' · ',array_filter([(string)($company['phone']??''),(string)($company['email']??''),(string)($company['website']??'')]))) ;
$pdf->setFill(...$navy);$pdf->fillRect(44,748,507,56);$pdf->setFill(1,1,1);$pdf->textAt($brand,20,58,780,true);$pdf->textAt($legal!==''&&$legal!==$brand?$legal:'Diseño · Impresión · Personalizados',8.5,58,765,false);if($contact!=='')$pdf->textAt($contact,7.5,58,752,false);
$pdf->setFill(...$red);$pdf->fillRect(404,758,147,46);$pdf->setFill(1,1,1);$pdf->textAt('RECIBO PREVIO',8.3,416,786,true);$pdf->textAt('SERVICIO + ANTICIPO',8.3,416,772,true);
$pdf->setFill(...$slate);$pdf->textAt('ORDEN',7.5,58,720,true);$pdf->textAt((string)$order['order_number'],11.5,58,705,true);$pdf->textAt('CLIENTE',7.5,205,720,true);$pdf->textAt((string)($order['customer_name']?:'Cliente'),10.5,205,705,true);$pdf->textAt('FECHA',7.5,405,720,true);$pdf->textAt(date('d/m/Y'),10.5,405,705,true);
$pdf->setFill(...$light);$pdf->fillRect(44,620,507,62);$pdf->setStroke(...$border);$pdf->rect(44,620,507,62);$pdf->setFill(...$red);$pdf->textAt('CONSTANCIA COMERCIAL',8.2,58,664,true);$pdf->setFill(...$navy);$pdf->textAt('Este documento resume el servicio solicitado, el pago registrado y el avance del pedido.',9.2,58,646,false);$pdf->textAt('No sustituye un CFDI.',7.8,58,632,false);
$y=595;$pdf->setFill(...$navy);$pdf->fillRect(44,$y-28,507,24);$pdf->setFill(1,1,1);$pdf->textAt('SERVICIO SOLICITADO',8.5,58,$y-18,true);$y-=42;
foreach($items as $idx=>$item){$lines=pdf_wrap((string)$item['description'],72);$rowH=max(24,count($lines)*11+8);$pdf->need($rowH+20);if($idx%2===0){$pdf->setFill(0.98,0.985,0.99);$pdf->fillRect(44,$y-$rowH+5,507,$rowH);} $pdf->setFill(...$navy);$ly=$y;foreach($lines as $line){$pdf->textAt($line,8,58,$ly,false);$ly-=11;} $pdf->textAt('Cant. '.number_format((float)$item['quantity'],3,'.',''),8,405,$y,false);$pdf->textAt(pdf_money((float)$item['subtotal']),8,490,$y,false);$pdf->setStroke(...$border);$pdf->line(44,$y-$rowH+5,551,$y-$rowH+5);$y-=$rowH;}
$y-=8;$pdf->setFill(...$navy);$pdf->fillRect(350,$y-108,201,108);$pdf->setFill(1,1,1);$pdf->textAt('RESUMEN DEL SERVICIO',8.5,364,$y-18,true);$pdf->textAt('Total',8.5,364,$y-40,false);$pdf->textAt(pdf_money((float)$finance['order_total']),9,469,$y-40,true);$pdf->textAt('Pagado / anticipo',8.5,364,$y-59,false);$pdf->setFill(...$green);$pdf->textAt(pdf_money((float)$finance['paid_total']),9,469,$y-59,true);$pdf->setFill(...$yellow);$pdf->textAt('Saldo pendiente',8.5,364,$y-78,false);$pdf->textAt(pdf_money((float)$finance['balance']),9,469,$y-78,true);
$pdf->setFill(...$red);$pdf->textAt($finance['first_payment']?'Primer pago registrado':'Anticipo pendiente',8,58,$y-28,true);$pdf->setFill(...$slate);if($finance['first_payment']){$fp=$finance['first_payment'];$pdf->textAt('Monto: '.pdf_money((float)$fp['amount']).' · '.(string)$fp['method_label'].' · '.date('d/m/Y',strtotime((string)$fp['payment_date'])),7.8,58,$y-43,false);}else{$pdf->textAt('Aún no existe un pago confirmado en el sistema.',7.8,58,$y-43,false);}
$contentY=min($y-132,470);$client=tracking_internal_to_client_stage(tracking_current_stage($orderId));$stages=tracking_client_stages();$pdf->setFill(...$red);$pdf->textAt('SEGUIMIENTO',8.3,58,$contentY,true);$contentY-=15;$pdf->setFill(...$navy);$pdf->textAt('Estado actual: '.$stages[$client]['label'],10.5,58,$contentY,true);$contentY-=15;if(!empty($order['due_date'])){$pdf->textAt('Fecha compromiso: '.date('d/m/Y',strtotime((string)$order['due_date'])),8,58,$contentY,false);$contentY-=12;}
if(!empty($order['payment_terms'])||!empty($order['delivery_time'])||!empty($order['delivery_place'])){$contentY-=4;$pdf->setFill(...$red);$pdf->textAt('ENTREGA Y PAGO',8.3,58,$contentY,true);$contentY-=14;$pdf->setFill(...$slate);foreach([!empty($order['payment_terms'])?'Pago: '.$order['payment_terms']:'',!empty($order['delivery_time'])?'Entrega: '.$order['delivery_time']:'',!empty($order['delivery_place'])?'Lugar: '.$order['delivery_place']:''] as $line){$line=trim((string)$line);if($line==='')continue;foreach(pdf_wrap($line,85) as $w){$pdf->textAt($w,7.8,58,$contentY,false);$contentY-=10;}}}
$pdf->setStroke(...$border);$pdf->line(44,55,551,55);$pdf->setFill(...$slate);$pdf->textAt('Constancia comercial previa · No sustituye un comprobante fiscal digital (CFDI).',6.8,44,42,false);$pdf->textAt($brand.' · '.$order['order_number'],6.8,44,30,false);
$data=$pdf->finish();header('Content-Type: application/pdf');header('Content-Length: '.strlen($data));header('Content-Disposition: attachment; filename="Recibo-previo-'.$order['order_number'].'.pdf"');header('Cache-Control: private, no-store, no-cache, must-revalidate, max-age=0');echo $data;
