CREATE TABLE IF NOT EXISTS cp_order_production_briefs (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id int(10) UNSIGNED NOT NULL,
  service_type varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'otro',
  product varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  quantity varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  dimensions varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  material varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  thickness varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  color varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  technique varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  finish varchar(190) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  sizes varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  customer_request text COLLATE utf8mb4_unicode_ci,
  design_status varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  design_version varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  design_approved_by int(10) UNSIGNED DEFAULT NULL,
  design_approved_at datetime DEFAULT NULL,
  priority varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'normal',
  instructions text COLLATE utf8mb4_unicode_ci,
  critical_instructions text COLLATE utf8mb4_unicode_ci,
  packaging text COLLATE utf8mb4_unicode_ci,
  delivery_internal text COLLATE utf8mb4_unicode_ci,
  extra_data text COLLATE utf8mb4_unicode_ci,
  created_by int(10) UNSIGNED DEFAULT NULL,
  updated_by int(10) UNSIGNED DEFAULT NULL,
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cp_order_production_brief_order (order_id),
  KEY idx_cp_order_production_briefs_service (service_type),
  KEY idx_cp_order_production_briefs_priority (priority),
  CONSTRAINT fk_cp_order_production_briefs_order FOREIGN KEY (order_id) REFERENCES cp_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_order_production_briefs_updated_by FOREIGN KEY (updated_by) REFERENCES cp_users (id) ON DELETE SET NULL,
  CONSTRAINT fk_cp_order_production_briefs_created_by FOREIGN KEY (created_by) REFERENCES cp_users (id) ON DELETE SET NULL,
  CONSTRAINT fk_cp_order_production_briefs_approved_by FOREIGN KEY (design_approved_by) REFERENCES cp_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cp_order_production_checklist (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id int(10) UNSIGNED NOT NULL,
  area varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  item_key varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  label varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  status varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  is_blocking tinyint(1) NOT NULL DEFAULT '0',
  completed_by int(10) UNSIGNED DEFAULT NULL,
  completed_at datetime DEFAULT NULL,
  sort_order int(11) NOT NULL DEFAULT '0',
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cp_order_production_checklist_item (order_id,item_key),
  KEY idx_cp_order_production_checklist_order (order_id),
  KEY idx_cp_order_production_checklist_area (area),
  CONSTRAINT fk_cp_order_production_checklist_order FOREIGN KEY (order_id) REFERENCES cp_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_order_production_checklist_completed_by FOREIGN KEY (completed_by) REFERENCES cp_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
