CREATE TABLE IF NOT EXISTS cp_payment_receipts (
  id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id int(10) UNSIGNED NOT NULL,
  payment_id int(10) UNSIGNED DEFAULT NULL,
  access_token char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  original_name varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL,
  file_path varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  mime_type varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  file_size int(10) UNSIGNED NOT NULL DEFAULT '0',
  status varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  note text COLLATE utf8mb4_unicode_ci,
  reviewed_by int(10) UNSIGNED DEFAULT NULL,
  reviewed_at datetime DEFAULT NULL,
  created_at datetime NOT NULL,
  updated_at datetime NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cp_payment_receipt_token (access_token),
  KEY idx_cp_payment_receipts_order (order_id),
  KEY idx_cp_payment_receipts_payment (payment_id),
  KEY idx_cp_payment_receipts_status (status),
  CONSTRAINT fk_cp_payment_receipts_order FOREIGN KEY (order_id) REFERENCES cp_orders (id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_payment_receipts_payment FOREIGN KEY (payment_id) REFERENCES cp_payments (id) ON DELETE SET NULL,
  CONSTRAINT fk_cp_payment_receipts_reviewed_by FOREIGN KEY (reviewed_by) REFERENCES cp_users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
