<?php
require '../app/core/bootstrap.php'; auth(); require '../app/core/layout.php';
$id=(int)($_GET['id']??0); if($id<1) redirect('compras.php');
$s=$pdo->prepare('SELECT c.*,COALESCE(p.nombre,"Sin proveedor") proveedor,p.rfc proveedor_rfc FROM compras c LEFT JOIN proveedores p ON p.id=c.proveedor_id WHERE c.id=?');$s->execute([$id]);$c=$s->fetch();if(!$c)redirect('compras.php');
$paid=purchasePaid($pdo,$id);$saldo=max(0,(float)$c['total']-$paid);$conceptos=$pdo->prepare('SELECT * FROM conceptos WHERE compra_id=? ORDER BY id');$conceptos->execute([$id]);$conceptos=$conceptos->fetchAll();
$pagos=$pdo->prepare('SELECT * FROM pagos WHERE compra_id=? ORDER BY fecha_pago DESC,id DESC');$pagos->execute([$id]);$pagos=$pagos->fetchAll();
head('Compra #'.$id);
?><div class="d-flex justify-content-between mb-3"><div><h2 class="h4 mb-1">Compra #<?=$id?></h2><div class="text-secondary">Detalle y seguimiento</div></div><a href="compras.php" class="btn btn-outline-secondary">← Volver</a></div>
<div class="alert <?=($saldo<=.01?'alert-success':($paid>0?'alert-info':'alert-warning'))?> d-flex justify-content-between"><strong>Estado: <?=ucfirst(e($c['estado']))?></strong><span>Saldo: <strong><?=money($saldo)?></strong></span></div>
<div class="row g-3"><div class="col-lg-6"><div class="card h-100"><div class="card-body"><h3 class="h5">Información de la compra</h3><hr><p><strong>Proveedor:</strong><br><?=e($c['proveedor'])?></p><p><strong>RFC emisor:</strong><br><?=e($c['rfc_emisor']?:'-')?></p><p><strong>Fecha de emisión:</strong><br><?=e($c['fecha_emision']?:'-')?></p><p><strong>Fecha de recepción:</strong><br><?=e($c['fecha_recepcion']?:'-')?></p><p><strong>Factura:</strong><br><?=e(trim(($c['serie']??'').' '.($c['folio']??''))?:'-')?></p><p class="mb-0"><strong>UUID:</strong><br><?=e($c['uuid']?:'-')?></p></div></div></div>
<div class="col-lg-6"><div class="card h-100"><div class="card-body"><h3 class="h5">Resumen financiero</h3><hr><div class="d-flex justify-content-between py-2"><span>Subtotal</span><strong><?=money($c['subtotal'])?></strong></div><div class="d-flex justify-content-between py-2"><span>IVA</span><strong><?=money($c['iva'])?></strong></div><div class="d-flex justify-content-between py-2 border-bottom"><span>Total</span><strong><?=money($c['total'])?></strong></div><div class="d-flex justify-content-between py-2"><span>Pagado</span><strong class="text-success"><?=money($paid)?></strong></div><div class="d-flex justify-content-between py-2"><span>Saldo pendiente</span><strong class="text-danger"><?=money($saldo)?></strong></div><?php if($saldo>.01):?><a class="btn btn-primary mt-3" href="pagos.php?compra_id=<?=$id?>">Registrar pago</a><?php endif?></div></div></div></div>
<div class="card mt-3"><div class="card-body"><h3 class="h5">Productos / conceptos</h3><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Descripción</th><th>Unidad</th><th>Cantidad</th><th>Precio unitario</th><th>Importe</th></tr></thead><tbody><?php foreach($conceptos as $x):?><tr><td><?=e($x['descripcion'])?></td><td><?=e($x['unidad'])?></td><td><?=e($x['cantidad'])?></td><td><?=money($x['valor_unitario'])?></td><td><?=money($x['importe'])?></td></tr><?php endforeach;if(!$conceptos):?><tr><td colspan="5" class="text-secondary">Sin conceptos registrados.</td></tr><?php endif?></tbody></table></div></div></div>
<div class="card mt-3"><div class="card-body"><h3 class="h5">Pagos registrados</h3><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Fecha</th><th>UUID pago</th><th>Parcialidad</th><th>Forma</th><th>Monto</th><th>Saldo insoluto</th></tr></thead><tbody><?php foreach($pagos as $p):?><tr><td><?=e($p['fecha_pago'])?></td><td><?=e($p['uuid_pago']?:'-')?></td><td><?=e($p['num_parcialidad']?:'-')?></td><td><?=e($p['forma_pago']?:'-')?></td><td class="text-success fw-semibold"><?=money($p['monto'])?></td><td><?=money($p['saldo_insoluto'])?></td></tr><?php endforeach;if(!$pagos):?><tr><td colspan="6" class="text-secondary">No hay pagos registrados.</td></tr><?php endif?></tbody></table></div></div></div>
<?php foot();
