<?php
require '../app/core/bootstrap.php'; auth(); require '../app/core/layout.php';
$q=trim($_GET['q']??''); $estado=$_GET['estado']??'';
$where=[];$params=[];
if($q!==''){ $where[]='(p.nombre LIKE ? OR c.uuid LIKE ? OR c.folio LIKE ? OR c.serie LIKE ? OR c.rfc_emisor LIKE ?)'; for($i=0;$i<5;$i++)$params[]='%'.$q.'%'; }
if(in_array($estado,['pendiente','parcial','pagada','cancelada'],true)){ $where[]='c.estado=?'; $params[]=$estado; }
$sql="SELECT c.*,COALESCE(p.nombre,'Sin proveedor') proveedor,COALESCE((SELECT SUM(m.monto) FROM pagos m WHERE m.compra_id=c.id),0) pagado FROM compras c LEFT JOIN proveedores p ON p.id=c.proveedor_id".($where?' WHERE '.implode(' AND ',$where):'')." ORDER BY c.fecha_emision DESC,c.id DESC";
$s=$pdo->prepare($sql);$s->execute($params);$rows=$s->fetchAll();
head('Compras');
?><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 mb-1">Seguimiento de compras</h2><div class="text-secondary">Control de compras, pagos y saldos pendientes</div></div><a class="btn btn-primary" href="xml.php">Importar XML</a></div>
<form class="card card-body mb-3"><div class="row g-2"><div class="col-md-5"><input name="q" value="<?=e($q)?>" class="form-control" placeholder="Proveedor, UUID, factura, RFC..."></div><div class="col-md-3"><select name="estado" class="form-select"><option value="">Todos los estados</option><?php foreach(['pendiente','parcial','pagada','cancelada'] as $x):?><option value="<?=$x?>" <?=$estado===$x?'selected':''?>><?=ucfirst($x)?></option><?php endforeach?></select></div><div class="col-md-2"><button class="btn btn-dark w-100">Filtrar</button></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="compras.php">Limpiar</a></div></div></form>
<div class="card"><div class="card-body p-0"><div class="table-responsive"><table class="table table-striped table-hover mb-0"><thead><tr><th>Fecha</th><th>Proveedor</th><th>Factura</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th><th></th></tr></thead><tbody><?php foreach($rows as $r):$saldo=max(0,(float)$r['total']-(float)$r['pagado']);?><tr><td><?=e($r['fecha_emision'])?></td><td><?=e($r['proveedor'])?></td><td><?=e(trim(($r['serie']??'').' '.($r['folio']??'')))?></td><td class="money"><?=money($r['total'])?></td><td class="money text-success"><?=money($r['pagado'])?></td><td class="money text-danger"><?=money($saldo)?></td><td><span class="status status-<?=e($r['estado'])?>"><?=ucfirst(e($r['estado']))?></span></td><td><a class="btn btn-sm btn-outline-primary" href="compra.php?id=<?=$r['id']?>">Ver</a></td></tr><?php endforeach;if(!$rows):?><tr><td colspan="8" class="text-center py-4 text-secondary">No hay compras.</td></tr><?php endif?></tbody></table></div></div></div>
<?php foot();
