<?php
require '../app/core/bootstrap.php'; auth(); require '../app/core/layout.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
 check_csrf();$cid=(int)$_POST['compra_id'];$monto=(float)$_POST['monto'];
 $s=$pdo->prepare('SELECT total FROM compras WHERE id=?');$s->execute([$cid]);$total=$s->fetchColumn();
 if($total===false) { flash('Compra no encontrada','danger'); redirect('pagos.php'); }
 $paid=purchasePaid($pdo,$cid);$saldo=max(0,(float)$total-$paid);
 if($monto<=0 || $monto>$saldo+0.01){flash('El monto debe ser mayor a cero y no superar el saldo pendiente.','danger');redirect('pagos.php?compra_id='.$cid);}
 $newSaldo=max(0,$saldo-$monto);
 $pdo->prepare('INSERT INTO pagos(compra_id,fecha_pago,monto,num_parcialidad,saldo_anterior,saldo_insoluto,forma_pago,moneda) VALUES(?,?,?,?,?,?,?,?)')->execute([$cid,$_POST['fecha_pago']?:date('Y-m-d H:i:s'),$monto,$_POST['num_parcialidad']?:null,$saldo,$newSaldo,$_POST['forma_pago']?:null,$_POST['moneda']?:'MXN']);
 syncPurchaseStatus($pdo,$cid);logAction($pdo,'Registrar pago','Compra #'.$cid.' por '.money($monto));flash('Pago registrado correctamente.');redirect('compra.php?id='.$cid);
}
$pre=(int)($_GET['compra_id']??0);$compras=$pdo->query("SELECT c.id,c.serie,c.folio,c.total,COALESCE((SELECT SUM(monto) FROM pagos p WHERE p.compra_id=c.id),0) pagado,pr.nombre proveedor FROM compras c LEFT JOIN proveedores pr ON pr.id=c.proveedor_id WHERE c.estado IN ('pendiente','parcial') ORDER BY c.fecha_emision DESC,c.id DESC")->fetchAll();
$recent=$pdo->query('SELECT p.*,c.serie,c.folio,pr.nombre proveedor FROM pagos p LEFT JOIN compras c ON c.id=p.compra_id LEFT JOIN proveedores pr ON pr.id=c.proveedor_id ORDER BY p.fecha_pago DESC,p.id DESC LIMIT 50')->fetchAll();
head('Pagos');
?><div class="row g-3"><div class="col-xl-5"><div class="card"><div class="card-body"><h2 class="h5">Registrar pago</h2><form method="post"><input type="hidden" name="csrf" value="<?=csrf()?>"><label class="form-label">Compra</label><select name="compra_id" id="compra" class="form-select mb-3" required><option value="">Seleccione...</option><?php foreach($compras as $c):$saldo=max(0,$c['total']-$c['pagado']);?><option value="<?=$c['id']?>" data-saldo="<?=$saldo?>" <?=$pre===$c['id']?'selected':''?>>#<?=$c['id']?> · <?=e(trim(($c['serie']??'').' '.($c['folio']??'')))?> · <?=e($c['proveedor'])?> · Saldo <?=money($saldo)?></option><?php endforeach?></select><label class="form-label">Saldo disponible</label><input id="saldo" class="form-control mb-3" readonly><label class="form-label">Monto</label><input name="monto" type="number" step="0.01" min="0.01" class="form-control mb-3" required><label class="form-label">Fecha y hora</label><input name="fecha_pago" type="datetime-local" class="form-control mb-3" value="<?=date('Y-m-d\TH:i')?>"><div class="row g-2"><div class="col"><label class="form-label">Forma de pago</label><input name="forma_pago" class="form-control" placeholder="03, 01..."></div><div class="col"><label class="form-label">Parcialidad</label><input name="num_parcialidad" class="form-control" placeholder="1"></div></div><button class="btn btn-primary w-100 mt-3">Guardar pago</button></form></div></div></div><div class="col-xl-7"><div class="card"><div class="card-body"><h2 class="h5">Últimos pagos</h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Fecha</th><th>Compra</th><th>Proveedor</th><th>Monto</th><th>Forma</th></tr></thead><tbody><?php foreach($recent as $p):?><tr><td><?=e($p['fecha_pago'])?></td><td>#<?=$p['compra_id']?></td><td><?=e($p['proveedor']?:'-')?></td><td class="text-success fw-semibold"><?=money($p['monto'])?></td><td><?=e($p['forma_pago']?:'-')?></td></tr><?php endforeach;if(!$recent):?><tr><td colspan="5" class="text-secondary">No hay pagos registrados.</td></tr><?php endif?></tbody></table></div></div></div></div></div>
<script>function upd(){const o=document.querySelector('#compra option:checked');document.getElementById('saldo').value=o?.dataset?.saldo?'$'+Number(o.dataset.saldo).toLocaleString('es-MX',{minimumFractionDigits:2}):''}document.getElementById('compra').addEventListener('change',upd);upd();</script>
<?php foot();
