USE colibrip_abcsistema;

CREATE TABLE IF NOT EXISTS cp_print_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id INT UNSIGNED NULL,
    quote_id INT UNSIGNED NULL,
    printer_name VARCHAR(190) NULL,
    material_name VARCHAR(190) NOT NULL DEFAULT 'Lona',
    printexp_job VARCHAR(190) NULL,
    printed_at DATETIME NOT NULL,
    dpi_x SMALLINT UNSIGNED NULL,
    dpi_y SMALLINT UNSIGNED NULL,
    print_program_pct DECIMAL(6,2) NULL,
    print_speed_m2_h DECIMAL(10,3) NULL,
    print_speed_m_h DECIMAL(10,3) NULL,
    print_mode VARCHAR(80) NULL,
    print_time_seconds INT UNSIGNED NULL,
    copy_number SMALLINT UNSIGNED NULL,
    copy_total SMALLINT UNSIGNED NULL,
    job_width_mm DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    job_length_mm DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    print_length_m DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    gross_m2 DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    result_status VARCHAR(40) NOT NULL DEFAULT 'good',
    waste_reason VARCHAR(80) NULL,
    waste_m2 DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    good_m2 DECIMAL(12,3) NOT NULL DEFAULT 0.000,
    notes TEXT NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_cp_print_jobs_printed_at (printed_at),
    KEY idx_cp_print_jobs_result_status (result_status),
    KEY idx_cp_print_jobs_order_id (order_id),
    KEY idx_cp_print_jobs_quote_id (quote_id),
    KEY idx_cp_print_jobs_printer (printer_name),
    KEY idx_cp_print_jobs_material (material_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
