<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/runtime.php';
require_once __DIR__ . '/../includes/actions.php';
require_once __DIR__ . '/../includes/quote_conditions.php';
require_auth();
quote_conditions_ensure_table();
$title='Condiciones comerciales';$error=null;$success=null;$action=(string)($_GET['action']??'list');$id=(int)($_GET['id']??0);$uid=(int)(current_user()['id']??0);
$empty=['name'=>'','payment_terms'=>'','delivery_time'=>'','delivery_place'=>'','terms'=>'','is_default'=>0,'enabled'=>1,'sort_order'=>0];$template=$empty;
if($action==='edit'&&$id>0){$found=quote_condition_get($id);if(!$found){$error='La condición comercial solicitada no existe.';$action='list';}else{$template=array_merge($empty,$found);}}
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    quote_conditions_ensure_table();
    if(!csrf_check($_POST['_csrf']??null)) throw new RuntimeException('La sesión del formulario expiró. Recarga la página.');
    $postId=(int)($_POST['id']??0);$data=['name'=>trim((string)($_POST['name']??'')),'payment_terms'=>trim((string)($_POST['payment_terms']??'')),'delivery_time'=>trim((string)($_POST['delivery_time']??'')),'delivery_place'=>trim((string)($_POST['delivery_place']??'')),'terms'=>trim((string)($_POST['terms']??'')),'is_default'=>isset($_POST['is_default'])?1:0,'enabled'=>isset($_POST['enabled'])?1:0,'sort_order'=>(int)($_POST['sort_order']??0)];
    if($data['name']==='') throw new RuntimeException('Escribe un nombre para la condición.');
    $pdo=db();$pdo->beginTransaction();if($data['is_default'])$pdo->exec('UPDATE cp_quote_condition_templates SET is_default=0');
    if($postId>0){$st=$pdo->prepare('UPDATE cp_quote_condition_templates SET name=?,payment_terms=?,delivery_time=?,delivery_place=?,terms=?,is_default=?,enabled=?,sort_order=?,updated_by=?,updated_at=NOW() WHERE id=?');$st->execute([$data['name'],$data['payment_terms']?:null,$data['delivery_time']?:null,$data['delivery_place']?:null,$data['terms']?:null,$data['is_default'],$data['enabled'],$data['sort_order'],$uid,$postId]);$savedId=$postId;}
    else{$st=$pdo->prepare('INSERT INTO cp_quote_condition_templates(name,payment_terms,delivery_time,delivery_place,terms,is_default,enabled,sort_order,created_by,updated_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');$st->execute([$data['name'],$data['payment_terms']?:null,$data['delivery_time']?:null,$data['delivery_place']?:null,$data['terms']?:null,$data['is_default'],$data['enabled'],$data['sort_order'],$uid,$uid]);$savedId=(int)$pdo->lastInsertId();}
    $pdo->commit();log_activity($postId>0?'update':'create','quote_condition_templates','Condición #'.$savedId.' guardada');redirect('/admin/condiciones_comerciales.php?saved=1');
  }catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'No se pudo guardar la condición.';$action=$id>0?'edit':'create';$template=array_merge($empty,['id'=>(int)($_POST['id']??0),'name'=>(string)($_POST['name']??''),'payment_terms'=>(string)($_POST['payment_terms']??''),'delivery_time'=>(string)($_POST['delivery_time']??''),'delivery_place'=>(string)($_POST['delivery_place']??''),'terms'=>(string)($_POST['terms']??''),'is_default'=>isset($_POST['is_default'])?1:0,'enabled'=>isset($_POST['enabled'])?1:0,'sort_order'=>(int)($_POST['sort_order']??0)]);}
}
if(isset($_GET['saved']))$success='Condición comercial guardada correctamente.';if(isset($_GET['deleted']))$success='Condición comercial eliminada.';
if($action==='delete'&&$id>0&&$_SERVER['REQUEST_METHOD']!=='POST'){try{$pdo=db();$st=$pdo->prepare('SELECT is_default FROM cp_quote_condition_templates WHERE id=?');$st->execute([$id]);$row=$st->fetch(PDO::FETCH_ASSOC);if($row&&(int)$row['is_default']===1)throw new RuntimeException('No puedes eliminar la predeterminada. Marca otra como predeterminada primero.');$pdo->prepare('DELETE FROM cp_quote_condition_templates WHERE id=?')->execute([$id]);log_activity('delete','quote_condition_templates','Condición #'.$id.' eliminada');redirect('/admin/condiciones_comerciales.php?deleted=1');}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'No se pudo eliminar la condición.';$action='list';}}
if($action==='default'&&$id>0&&$_SERVER['REQUEST_METHOD']!=='POST'){try{quote_condition_set_default($id);log_activity('update','quote_condition_templates','Condición #'.$id.' predeterminada');redirect('/admin/condiciones_comerciales.php?saved=1');}catch(Throwable $e){$error='No se pudo establecer la condición predeterminada.';$action='list';}}
$rows=$action==='list'?quote_condition_templates(true):[];require __DIR__ . '/../includes/header.php';
?>
<link rel="stylesheet" href="/assets/css/cotizaciones.css?v=20260919-cv2">
<div class="quote-toolbar"><div><span class="eyebrow">CONFIGURACIÓN · COTIZACIONES</span><h2>Condiciones comerciales</h2><p class="muted">Administra plantillas reutilizables para entrega, pago y términos comerciales.</p></div><div class="quote-toolbar-actions"><a class="btn btn-primary" href="/admin/condiciones_comerciales.php?action=create">＋ Nueva condición</a></div></div>
<?php if($error): ?><div class="notice danger"><?=e($error)?></div><?php endif; ?><?php if($success): ?><div class="notice"><span class="ok">✓</span> <?=e($success)?></div><?php endif; ?>
<?php if($action==='create'||$action==='edit'): ?><section class="card"><div class="section-heading"><div><span class="eyebrow">PLANTILLA</span><h3><?=$action==='edit'?'Editar condición':'Nueva condición comercial'?></h3></div></div><form method="post"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e((string)($template['id']??0))?>"><div class="form-grid"><div class="field field-full"><label>Nombre *</label><input name="name" maxlength="150" required value="<?=e((string)$template['name'])?>"></div><div class="field"><label>Condiciones de pago</label><input name="payment_terms" maxlength="190" value="<?=e((string)$template['payment_terms'])?>"></div><div class="field"><label>Tiempo de entrega</label><input name="delivery_time" maxlength="190" value="<?=e((string)$template['delivery_time'])?>"></div><div class="field field-full"><label>Lugar de entrega</label><input name="delivery_place" maxlength="190" value="<?=e((string)$template['delivery_place'])?>"></div><div class="field field-full"><label>Condiciones comerciales</label><textarea name="terms" rows="7"><?=e((string)$template['terms'])?></textarea></div><div class="field"><label>Orden</label><input type="number" name="sort_order" value="<?=e((string)$template['sort_order'])?>"></div><div class="field checkbox-row"><label><input type="checkbox" name="enabled" value="1" <?=((int)$template['enabled']===1?'checked':'')?>> Activa</label><label><input type="checkbox" name="is_default" value="1" <?=((int)$template['is_default']===1?'checked':'')?>> Predeterminada</label></div></div><div class="form-actions"><a class="btn btn-secondary" href="/admin/condiciones_comerciales.php">Cancelar</a><?=save_button('Guardar condición')?></div></form></section>
<?php else: ?><section class="card"><div class="section-heading"><div><span class="eyebrow">PLANTILLAS DISPONIBLES</span><h3>Condiciones reutilizables</h3><p class="muted">La predeterminada se aplica automáticamente a una cotización nueva.</p></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Plantilla</th><th>Pago</th><th>Entrega</th><th>Estado</th><th>Acciones</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><strong><?=e((string)$r['name'])?></strong><?php if((int)$r['is_default']===1): ?><span class="status-badge status-paid" style="margin-left:8px">Predeterminada</span><?php endif; ?><div class="muted"><?=nl2br(e((string)($r['terms']??'')))?></div></td><td><?=e((string)($r['payment_terms']??'—'))?></td><td><?=e((string)($r['delivery_time']??'—'))?><br><?=e((string)($r['delivery_place']??'—'))?></td><td><?=((int)$r['enabled']===1?'Activa':'Inactiva')?></td><td class="actions-cell"><a class="btn btn-sm btn-secondary" href="/admin/condiciones_comerciales.php?action=edit&id=<?=((int)$r['id'])?>">Editar</a><?php if((int)$r['is_default']!==1): ?><a class="btn btn-sm btn-primary" href="/admin/condiciones_comerciales.php?action=default&id=<?=((int)$r['id'])?>">Predeterminada</a><a class="btn btn-sm btn-danger" href="/admin/condiciones_comerciales.php?action=delete&id=<?=((int)$r['id'])?>" onclick="return confirm('¿Eliminar esta plantilla?')">Eliminar</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="5">No hay plantillas disponibles.</td></tr><?php endif; ?></tbody></table></div></section><?php endif; ?><?php require __DIR__ . '/../includes/footer.php'; ?>
