<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/runtime.php';
require_once __DIR__ . '/../includes/actions.php';
require_auth();
$title='Productos';$pdo=db();$error=null;$success=null;$action=(string)($_GET['action']??'list');$id=(int)($_GET['id']??0);$q=trim((string)($_GET['q']??''));
$product=['category_id'=>'','name'=>'','sku'=>'','description'=>'','sale_price'=>'','purchase_price'=>'','pricing_type'=>'fixed','visible_web'=>0,'enabled'=>1];$imagePath='';
function product_upload(array $file): ?string {
  if(($file['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)return null;
  if(($file['error']??0)!==UPLOAD_ERR_OK)throw new RuntimeException('No se pudo subir la imagen.');
  if((int)($file['size']??0)>5*1024*1024)throw new RuntimeException('La imagen supera el máximo de 5 MB.');
  $finfo=new finfo(FILEINFO_MIME_TYPE);$mime=$finfo->file($file['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
  if(!isset($allowed[$mime]))throw new RuntimeException('Formato de imagen no permitido. Usa JPG, PNG o WEBP.');
  $dir=__DIR__.'/../uploads/products';if(!is_dir($dir)&&!mkdir($dir,0755,true))throw new RuntimeException('No se pudo crear la carpeta de imágenes.');
  $name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];$dest=$dir.'/'.$name;if(!move_uploaded_file($file['tmp_name'],$dest))throw new RuntimeException('No se pudo guardar la imagen.');
  return '/uploads/products/'.$name;
}
function product_delete_file(?string $path):void{if(!$path)return;$base=realpath(__DIR__.'/../uploads/products');$file=realpath(__DIR__.'/..'.$path);if($base&&$file&&str_starts_with($file,$base.DIRECTORY_SEPARATOR)&&is_file($file))@unlink($file);}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $form=(string)($_POST['form_action']??'');$id=(int)($_POST['id']??0);
 if(!csrf_check($_POST['_csrf']??null)){$error='La sesión del formulario expiró. Recarga la página.';$action=$form==='save'&&$id>0?'edit':'create';}
 elseif($form==='delete')try{$s=$pdo->prepare('SELECT id FROM cp_products WHERE id=?');$s->execute([$id]);if(!$s->fetch())throw new RuntimeException('Producto no encontrado.');$pdo->prepare('DELETE FROM cp_products WHERE id=?')->execute([$id]);log_activity('delete','products','Producto #'.$id.' eliminado');redirect('/admin/productos.php?deleted=1');}catch(Throwable $e){$error=$e->getMessage();$action='list';}
 elseif($form==='save'){
  $product=['category_id'=>(int)($_POST['category_id']??0)?:null,'name'=>trim((string)($_POST['name']??'')),'sku'=>trim((string)($_POST['sku']??'')),'description'=>trim((string)($_POST['description']??'')),'sale_price'=>trim((string)($_POST['sale_price']??'')),'purchase_price'=>trim((string)($_POST['purchase_price']??'')),'pricing_type'=>trim((string)($_POST['pricing_type']??'fixed')),'visible_web'=>isset($_POST['visible_web'])?1:0,'enabled'=>isset($_POST['enabled'])?1:0];$action=$id>0?'edit':'create';
  $validTypes=['fixed','variable','calculated','project'];
  if($product['name']==='')$error='El nombre del producto es obligatorio.';elseif(!in_array($product['pricing_type'],$validTypes,true))$error='Tipo de precio inválido.';elseif($product['sale_price']!==''&&!is_numeric($product['sale_price']))$error='El precio de venta no es válido.';elseif($product['purchase_price']!==''&&!is_numeric($product['purchase_price']))$error='El costo no es válido.';else try{
    $newImage=product_upload($_FILES['image']??[]);
    if($id>0){$old=$pdo->prepare('SELECT * FROM cp_products WHERE id=?');$old->execute([$id]);$found=$old->fetch();if(!$found)throw new RuntimeException('Producto no encontrado.');$s=$pdo->prepare('UPDATE cp_products SET category_id=?,name=?,sku=?,description=?,sale_price=?,purchase_price=?,pricing_type=?,visible_web=?,enabled=?,updated_at=NOW() WHERE id=?');$s->execute([$product['category_id'],$product['name'],$product['sku']?:null,$product['description']?:null,$product['sale_price']!==''?$product['sale_price']:null,$product['purchase_price']!==''?$product['purchase_price']:null,$product['pricing_type'],$product['visible_web'],$product['enabled'],$id]);if($newImage){$oldImg=$pdo->prepare('SELECT path FROM cp_product_images WHERE product_id=? AND enabled=1 ORDER BY sort_order,id LIMIT 1');$oldImg->execute([$id]);product_delete_file($oldImg->fetchColumn()?:null);$pdo->prepare('DELETE FROM cp_product_images WHERE product_id=?')->execute([$id]);$im=$pdo->prepare('INSERT INTO cp_product_images(product_id,path,alt_text,sort_order,enabled,created_at) VALUES(?,?,?,?,1,NOW())');$im->execute([$id,$newImage,$product['name'],0]);}log_activity('update','products','Producto #'.$id.' actualizado');redirect('/admin/productos.php?saved=updated');}
    else{$s=$pdo->prepare('INSERT INTO cp_products(source_type,category_id,name,sku,description,sale_price,purchase_price,pricing_type,visible_web,enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())');$s->execute(['local',$product['category_id'],$product['name'],$product['sku']?:null,$product['description']?:null,$product['sale_price']!==''?$product['sale_price']:null,$product['purchase_price']!==''?$product['purchase_price']:null,$product['pricing_type'],$product['visible_web'],$product['enabled']]);$newId=(int)$pdo->lastInsertId();if($newImage){$im=$pdo->prepare('INSERT INTO cp_product_images(product_id,path,alt_text,sort_order,enabled,created_at) VALUES(?,?,?,?,1,NOW())');$im->execute([$newId,$newImage,$product['name'],0]);}log_activity('create','products','Producto #'.$newId.' creado');redirect('/admin/productos.php?saved=created');}
  }catch(Throwable $e){$error='No se pudo guardar el producto: '.$e->getMessage();}
 }
}
if(isset($_GET['deleted']))$success='Producto eliminado correctamente.';if(($_GET['saved']??'')==='created')$success='Producto creado correctamente.';if(($_GET['saved']??'')==='updated')$success='Producto actualizado correctamente.';
$categories=$pdo->query("SELECT id,name FROM cp_categories WHERE type='product' AND enabled=1 ORDER BY sort_order,name")->fetchAll();
if(($action==='edit'||$action==='create')&&$id>0&&$_SERVER['REQUEST_METHOD']!=='POST'){$s=$pdo->prepare('SELECT * FROM cp_products WHERE id=?');$s->execute([$id]);$found=$s->fetch();if(!$found){$error='El producto no existe.';$action='list';}else{$product=array_merge($product,$found);$im=$pdo->prepare('SELECT path FROM cp_product_images WHERE product_id=? AND enabled=1 ORDER BY sort_order,id LIMIT 1');$im->execute([$id]);$imagePath=(string)($im->fetchColumn()?:'');}}
$rows=[];if($action==='list'){if($q!==''){$s=$pdo->prepare("SELECT p.*,c.name category_name,(SELECT path FROM cp_product_images i WHERE i.product_id=p.id AND i.enabled=1 ORDER BY i.sort_order,i.id LIMIT 1) image_path FROM cp_products p LEFT JOIN cp_categories c ON c.id=p.category_id WHERE p.name LIKE ? OR p.sku LIKE ? OR p.description LIKE ? ORDER BY p.id DESC LIMIT 100");$like='%'.$q.'%';$s->execute([$like,$like,$like]);$rows=$s->fetchAll();}else{$rows=$pdo->query("SELECT p.*,c.name category_name,(SELECT path FROM cp_product_images i WHERE i.product_id=p.id AND i.enabled=1 ORDER BY i.sort_order,i.id LIMIT 1) image_path FROM cp_products p LEFT JOIN cp_categories c ON c.id=p.category_id ORDER BY p.id DESC LIMIT 100")->fetchAll();}}
$typeLabels=['fixed'=>'Precio fijo','variable'=>'Precio variable','calculated'=>'Calculado','project'=>'Proyecto cotizable'];
require __DIR__.'/../includes/header.php';
?>
<?php if($action==='create'||$action==='edit'): ?>
<div class="toolbar"><div class="toolbar-title"><span class="eyebrow">FASE 3 · CATÁLOGO</span><h2><?= $action==='edit'?'Editar producto':'Nuevo producto' ?></h2><span class="muted">Producto independiente de Akaunting.</span></div><div class="toolbar-actions"><?=cancel_button('/admin/productos.php')?></div></div>
<?php if($error): ?><div class="notice danger" style="margin-bottom:14px"><?=e($error)?></div><?php endif; ?>
<div class="card form-card"><form method="post" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="form_action" value="save"><input type="hidden" name="id" value="<?=e((string)$id)?>"><div class="form-grid"><div class="field full"><label>Nombre del producto <span class="required">*</span></label><input data-auto-focus name="name" maxlength="190" value="<?=e((string)$product['name'])?>" required></div><div class="field"><label>SKU</label><input name="sku" maxlength="100" value="<?=e((string)$product['sku'])?>"></div><div class="field"><label>Categoría</label><select name="category_id"><option value="">Sin categoría</option><?php foreach($categories as $c): ?><option value="<?=e((string)$c['id'])?>" <?=((int)$product['category_id']===(int)$c['id']?'selected':'')?>><?=e($c['name'])?></option><?php endforeach; ?></select></div><div class="field"><label>Tipo de precio</label><select name="pricing_type"><?php foreach($typeLabels as $k=>$v): ?><option value="<?=e($k)?>" <?=((string)$product['pricing_type']===$k?'selected':'')?>><?=e($v)?></option><?php endforeach; ?></select></div><div class="field"><label>Precio de venta</label><input type="number" step="0.01" min="0" name="sale_price" value="<?=e((string)$product['sale_price'])?>"></div><div class="field"><label>Costo interno</label><input type="number" step="0.01" min="0" name="purchase_price" value="<?=e((string)$product['purchase_price'])?>"></div><div class="field full"><label>Descripción</label><textarea name="description" rows="5" style="width:100%;box-sizing:border-box;padding:11px 12px;border-radius:10px;border:1px solid #31577e;background:#09182b;color:#eef7ff;resize:vertical"><?=e((string)$product['description'])?></textarea></div><div class="field"><label>Imagen principal</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"><span class="help">JPG, PNG o WEBP. Máximo 5 MB.</span><?php if($imagePath): ?><div style="margin-top:8px"><img src="<?=e($imagePath)?>" alt="" style="max-width:160px;max-height:120px;border-radius:10px;border:1px solid #31577e;object-fit:cover"></div><?php endif; ?></div><div class="field"><label>Publicación</label><label style="display:flex;align-items:center;gap:8px"><input type="checkbox" name="visible_web" value="1" <?=((int)$product['visible_web']===1?'checked':'')?> style="width:auto"> Visible en web</label><label style="display:flex;align-items:center;gap:8px;margin-top:8px"><input type="checkbox" name="enabled" value="1" <?=((int)$product['enabled']===1?'checked':'')?> style="width:auto"> Producto activo</label></div></div><div class="form-actions"><?=cancel_button('/admin/productos.php')?><?=save_button($action==='edit'?'Guardar cambios':'Crear producto')?></div></form></div>
<?php else: ?>
<div class="toolbar"><div class="toolbar-title"><span class="eyebrow">FASE 3 · CATÁLOGO</span><h2>Productos</h2><span class="muted">Catálogo propio de Colibrí Print, preparado para cotización y web.</span></div><div class="toolbar-actions"><?=action_button('Categorías','/admin/categorias.php','btn btn-secondary')?><?=action_button('Nuevo producto','/admin/productos.php?action=create','btn')?></div></div>
<?php if($error): ?><div class="notice danger" style="margin-bottom:14px"><?=e($error)?></div><?php endif; ?><?php if($success): ?><div class="notice" style="margin-bottom:14px"><span class="ok">✓</span> <?=e($success)?></div><?php endif; ?>
<div class="card" style="margin-bottom:14px"><form class="search-form" method="get"><input type="search" name="q" value="<?=e($q)?>" placeholder="Buscar producto, SKU o descripción"><button class="btn btn-secondary">Buscar</button><?php if($q!==''): ?><?=cancel_button('/admin/productos.php')?><?php endif; ?></form></div>
<div class="card table-wrap"><table class="table"><thead><tr><th>Producto</th><th>SKU</th><th>Categoría</th><th>Precio</th><th>Tipo</th><th>Estado</th><th class="actions-cell">Acciones</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><div style="display:flex;align-items:center;gap:10px"><?php if($r['image_path']): ?><img src="<?=e($r['image_path'])?>" alt="" style="width:48px;height:48px;border-radius:8px;object-fit:cover;border:1px solid #31577e"><?php endif; ?><div><strong><?=e($r['name'])?></strong><div class="muted" style="font-size:12px"><?=e(mb_strimwidth((string)($r['description']??''),0,80,'…'))?></div></div></div></td><td><?=e($r['sku']?:'—')?></td><td><?=e($r['category_name']?:'Sin categoría')?></td><td><?= $r['sale_price']!==null?'$'.number_format((float)$r['sale_price'],2):'—' ?></td><td><?=e($typeLabels[$r['pricing_type']]??$r['pricing_type'])?></td><td><span class="<?=((int)$r['enabled']===1?'status-active':'status-inactive')?>"><?=((int)$r['enabled']===1?'Activo':'Inactivo')?></span><?=((int)$r['visible_web']===1?' · Web':'')?></td><td class="actions-cell"><div class="actions"><?=edit_button('/admin/productos.php?action=edit&id='.(int)$r['id'])?><form method="post" style="display:inline;margin:0"><input type="hidden" name="_csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="form_action" value="delete"><input type="hidden" name="id" value="<?=e((string)$r['id'])?>"><button class="btn btn-sm btn-delete" type="submit" data-confirm="¿Borrar el producto <?=e($r['name'])?>? Esta acción no se puede deshacer.">Borrar</button></form></div></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="7" class="empty">No hay productos en el catálogo.</td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?><?php require __DIR__.'/../includes/footer.php'; ?>
